const input=document.getElementById("input"),stats=document.getElementById("stats"),clearBtn=document.getElementById("clear"),generateBtn=document.getElementById("generate"),status=document.getElementById("status");
const aliases={"номер ктк":["номер ктк","ктк"],"ref":["ref","реф","букинг"],"статус":["статус","клиент","получатель"],"фактический объем, м3":["фактический объем, м3","фактический объем м3","объем, м3","объем м3"],"вес, кг":["вес, кг","вес кг","вес"],"кол-во мест":["кол-во мест","количество мест","мест"]};
function norm(v){return String(v??"").replace(/\uFEFF/g,"").replace(/\u00A0/g," ").replace(/\r?\n/g," ").trim().toLowerCase().replace(/\s+/g," ")}
function parse(text){return text.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split("\n").map(x=>x.split("\t").map(v=>v.trim())).filter(r=>r.some(v=>v!==""))}
function findCol(headers,name){const h=headers.map(norm), opts=(aliases[name]||[name]).map(norm);let i=h.findIndex(x=>opts.includes(x));if(i>=0)return i;i=h.findIndex(x=>opts.some(o=>x.includes(o)||o.includes(x)));return i}
function detect(headers){const req=["номер ктк","ref","статус","фактический объем, м3","вес, кг","кол-во мест"],result={},missing=[];for(const n of req){const i=findCol(headers,n);if(i<0)missing.push(n);else result[n]=i}return {result,missing}}
function update(){const rows=parse(input.value);if(!rows.length){stats.textContent="Данные не введены";generateBtn.disabled=true;return}const {missing}=detect(rows[0]),data=rows.slice(1);stats.textContent=missing.length?`${data.length} строк · не найдены: ${missing.join(", ")}`:`${data.length} записей · ${rows[0].length} столбцов · все необходимые поля найдены`;generateBtn.disabled=!!missing.length||!data.length;status.textContent=""}
input.addEventListener("input",update);clearBtn.onclick=()=>{input.value="";update();input.focus()};
async function make(){const rows=parse(input.value);if(!rows.length)throw Error("Сначала вставьте данные из Excel.");const headers=rows[0],det=detect(headers);if(det.missing.length)throw Error("Не найдены необходимые поля: "+det.missing.join(", "));const data=rows.slice(1);const res=await fetch("templates/проработка.xlsx");if(!res.ok)throw Error("Не удалось загрузить шаблон «Проработка».");const wb=XLSX.read(new Uint8Array(await res.arrayBuffer()),{type:"array"}),sh=wb.Sheets[wb.SheetNames[0]],rg=XLSX.utils.decode_range(sh["!ref"]),ths=[];for(let c=rg.s.c;c<=rg.e.c;c++)ths.push(sh[XLSX.utils.encode_cell({r:rg.s.r,c})]?.v??"");
const targets={"номер ктк":"номер ктк","ref":"Букинг","статус":"Клиент","фактический объем, м3":"объем, м3","вес, кг":"вес, кг","кол-во мест":"кол-во мест"},tc={};for(const [s,t] of Object.entries(targets)){const i=findCol(ths,t);if(i<0)throw Error("В шаблоне не найдена колонка «"+t+"».");tc[s]=i}
data.forEach((row,ri)=>{for(const s of Object.keys(targets)){const addr=XLSX.utils.encode_cell({r:rg.s.r+1+ri,c:tc[s]}),v=row[det.result[s]]??"";sh[addr]={t:typeof v==="number"?"n":"s",v}}});
const out=XLSX.write(wb,{bookType:"xlsx",type:"array"}),blob=new Blob([out],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Проработка_готово.xlsx";document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);return data.length}
generateBtn.onclick=async()=>{generateBtn.disabled=true;generateBtn.textContent="Формируем…";try{status.textContent=`Готово. Сформировано записей: ${await make()}. Файл скачивается.`}catch(e){status.textContent=e.message}finally{generateBtn.textContent="Сформировать документ";update()}};